hash-format = "sha256"

[[files]]
file = "config/inventoryprofilesnext/integrationHints/exampleIntegrationHints.json"
hash = "ca413dea02cce69c69dccdc525fb0ec013236876eff2d142772c68db3d772d3a"

[[files]]
file = "config/inventoryprofilesnext/integrationHints/player-defined.json"
hash = "10cd1a196f18989738bf8e964d1ab5c9aa51a44506e3bb1f5d1a3fe2275649b2"

[[files]]
file = "config/inventoryprofilesnext/inventoryprofiles.json"
hash = "b5be17a791130e0eda4e9506548a99322a11a3064dd910dc90c616e8fcc5fbcc"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "3a1d056ae1f4a94074f21f65897029cda642ad8b876e194b2d32f2807a72c7c5"
metafile = true

[[files]]
file = "mods/areas.pw.toml"
hash = "346a05ecdd72d457bd3d16e2f349981895de9d336b99b740bcca10c3b72c2d36"
metafile = true

[[files]]
file = "mods/armor-poser.pw.toml"
hash = "1c8d8a1154d286801963180efa1c8cb989624e4f836b79593180a04e80b3b8db"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "4585c3d720fd1b9333460242529af0d65fb5b710cbcb140dec43328ea18ff864"
metafile = true

[[files]]
file = "mods/beautify-refabricated.pw.toml"
hash = "d4b462af6dec47525479f1de355a2499ec44fd199ad71d8b1c9f2e526d922648"
metafile = true

[[files]]
file = "mods/cc-tweaked-1.21.11-fabric-1.116.2-a072b116fae75fbf020d7be1acc69753fefc4641.jar"
hash = "ae35851c44ab2934878a79a9e8b201de4d3e2ede69f6531d40dbe1ae95be6c7d"

[[files]]
file = "mods/cc-tweaked.pw.toml"
hash = "a2faf8f11a13b35ae5c0fe28f9b7efad0eea71f122e01e8e56431c7a0c8e913c"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "9c6569f98414d271ed0a420e45541511b67b8c43f0fb8a5f6fa8346d18c2390a"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "2ab64ec838a047951a4beac23be9f5e453b8154022fdd9447907b05ab7f2ae29"
metafile = true

[[files]]
file = "mods/create-fly.pw.toml"
hash = "1d24c8e884daf81e81869a048b03049abf4b949e3d262ce52742075a00ec1dac"
metafile = true

[[files]]
file = "mods/diagonal-fences.pw.toml"
hash = "42411a515ccaf1e9fb7711a17dfbe1af596bdf8dff588e841ffe8242d2235788"
metafile = true

[[files]]
file = "mods/diagonal-walls.pw.toml"
hash = "7d2e2d1213f0b2805df71ab9fb72eb88e1d1a72e917185dd051751f176d5112e"
metafile = true

[[files]]
file = "mods/easy-shulker-boxes.pw.toml"
hash = "9fdf4cc2e022db5ed038eb89273cd7eb9b973018cd854cb537aa38fd88bed813"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "d1403e904e626fe04ef67fce2b7c28717622ab8182f9af13d2b2270aff190f36"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "b70bae30a8cf2ae2f5547df58b6e753a1af09d434dcef196c7db9b65d15f7674"
metafile = true

[[files]]
file = "mods/farmers-delight-refabricated.pw.toml"
hash = "318c98995e6d554654dc38be43f9f6293808c432f0808bf775e81b93fef00e66"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "84c5e805fce485988261db701dbb0c7361de344a29726196354725199b7e7c17"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "d5b9d00f2bf8d72afad93015c2e02aa020c1b38b51372efde7e99b41380f4f7d"
metafile = true

[[files]]
file = "mods/framework.pw.toml"
hash = "d2a9be0aaa26b3fc1d7b315798a3a7ccd741c2abdb91ffb13918a490d072b2c8"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "966811e1c341c7cfccf62bab55d32e476ea891e5b3d891c0a024da7e317d89d8"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "f1fed5a7024f4acc3ebd3a537dc94232f47d8f6e991e5cebf78713342b8e40c7"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "07367ae2dea9e89c2dab96dd336e003b5e16ae821327f373e3ec616624d8247b"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "7479698240d4d2ba97dedf74eb89420e36a3bcaba55e7d5c163f82bafb369812"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "8acca905def364e9d68654e96d31c0d3b76118ccfd346c129995c205b89caf2e"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "813bcf9a0eded32aa133b3c4ed76d9790cbc34c7f9c94b235779e78bf50131a8"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "14b48c0f5a8fca3ed9c9350acc4b2334187ee8d96999b368f620daa1d0d36299"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
hash = "0345c6ec5a65d24c9254ffecb26a9618527f305295bc361f99e5cd91c2a85180"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
hash = "b886722521a83c6f7b952eba3fc1226c5baa2a54c637b14cfe306dcc999cf7d9"
metafile = true

[[files]]
file = "mods/particle-rain.pw.toml"
hash = "0cbf997f864685142aa51902ec72ed2947938331351f3fef5ea201a3d2cb4c51"
metafile = true

[[files]]
file = "mods/pneumono_core.pw.toml"
hash = "609c5e2a83445b58c11de14d1ae589d96d2b97490bce67ffd1b20d1b466746e7"
metafile = true

[[files]]
file = "mods/pneumono_gravestones.pw.toml"
hash = "30a4bdc3c91d9a2abd372f21104d9d6832fe88e10165b191be515e5e0b21b0a3"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "0f6a2d20967ed5dd408b78df9b1accd8db79554e4bb5b6d8c5500a4cf7a81133"
metafile = true

[[files]]
file = "mods/refurbished-furniture.pw.toml"
hash = "c648a21dfdc2501ed028420bf42c646576f6e697034c3c0eb1194f5b10f70c03"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "eaa8e9db81efd67ffd85fdd2205c04f96cc9b0501df7db61dae220f6db879167"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "5c1ab2c7bc3e3db1658fd574794cda03d95d306d46250474e80a143091513ee1"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "818950091879b542d9485edfa247ed930225e79cf452c49b6243013148616d81"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "ad3a1ebff5268c2575cdd6da51d1c71a5a6e598a314e0a098915a89550495344"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "bd943578f5e8df6c99624ad762c1cf1a096ed629b78645cc4985b97ccca07d5e"
metafile = true

[[files]]
file = "servers.dat"
hash = "c9821016c873fca9a3f7534de3a84d06fbb3ef162c1c245844aeb70f46d77a37"

[[files]]
file = "shaders/ComplementaryReimagined_r5.5.1.zip"
hash = "20897248a5fe91b33bf7fd4b75959c30aa2003df195297979a410ee37d3bb62f"

[[files]]
file = "shaders/ComplementaryUnbound_r5.5.1.zip"
hash = "61d133b24b6a92e46a3d7df791bb2ff163bbba10eed59df979b9bd727c24fbaf"
