hash-format = "sha256"

[[files]]
file = "config/inventoryprofilesnext/integrationHints/exampleIntegrationHints.json"
hash = "ca413dea02cce69c69dccdc525fb0ec013236876eff2d142772c68db3d772d3a"

[[files]]
file = "config/inventoryprofilesnext/integrationHints/player-defined.json"
hash = "10cd1a196f18989738bf8e964d1ab5c9aa51a44506e3bb1f5d1a3fe2275649b2"

[[files]]
file = "config/inventoryprofilesnext/inventoryprofiles.json"
hash = "b5be17a791130e0eda4e9506548a99322a11a3064dd910dc90c616e8fcc5fbcc"

[[files]]
file = "mods/amendments.pw.toml"
hash = "fb413ba504cfaae8ab4d96ede3944b8eb15fa4238ae02b4331bdad2549876f2e"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "b74cf679245fc0b470b94f7d3ef427954c56f6c38806105c95cf38685d99e555"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "6d3a1c92eee4dd671253c41ec000ae48064a33c45263d6adce5cad466395169d"
metafile = true

[[files]]
file = "mods/areas.pw.toml"
hash = "4f07285594f595c2f8dce881109e5a2c6075b365316bd145187b0bb9b90e2fa9"
metafile = true

[[files]]
file = "mods/armor-poser.pw.toml"
hash = "da96726d9a02eeaeee62cf2fafc616ca8c979f56f1b22afd669c117eeb3057b8"
metafile = true

[[files]]
file = "mods/armourers-workshop.pw.toml"
hash = "fcd0c25f93c2ddc9811609b774df84a0eb362cff602e8cdf2ec84816ecc9a6f3"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "6f1b842bcab873b16f0898c910be335d4d80250764f3dbf517584359704b7fc3"
metafile = true

[[files]]
file = "mods/beautify.pw.toml"
hash = "f3526ee866b1bf9399c7ef9c4c30cfcc9e6be091b7fc540f918d4a2eddf2a5d1"
metafile = true

[[files]]
file = "mods/brewin-and-chewin.pw.toml"
hash = "ef7c9b68b65e7baab19dc84903f068de6714e6f306052940f53c747743d3025e"
metafile = true

[[files]]
file = "mods/carry-on.pw.toml"
hash = "ebb87ace42558adf31374280e9e9dc91894af8ee7ae0157089194082df9af548"
metafile = true

[[files]]
file = "mods/cc-tweaked.pw.toml"
hash = "667344dcc91381c11ea871326f828a72e3386dfc450b7e08ca1ea409f66cc2d3"
metafile = true

[[files]]
file = "mods/cerbons-api.pw.toml"
hash = "479dab388743fb59d3399d2d87a0a7dc0819a4184b74f734fa9cc1eecdd6f6f6"
metafile = true

[[files]]
file = "mods/cerbons-better-beacons.pw.toml"
hash = "5c92ca1ecca22abcb1c7dd8333042d2a5b5c5259fdcc44ebb497cd1859606460"
metafile = true

[[files]]
file = "mods/chimes.pw.toml"
hash = "5f0d87ae88243df2390d5d8a2b0fdf312382ccae83084c9a1ba807c08fbcc013"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "75181b55e0407d1fca1e2f346c6501f919f5109545990ddfb66db9cd1b771f8a"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "e186e71f238d2f504ca6c2ee19d20266e5132f7655653f8179c0b8f6a295daae"
metafile = true

[[files]]
file = "mods/connector-extras.pw.toml"
hash = "4e257681e2a89397d7b52e57f187b7b1e3e3f901b56940a3294abda717992c6f"
metafile = true

[[files]]
file = "mods/connector.pw.toml"
hash = "d8b48452b5e57c299e6d81170014d166ccac886972ee0093b2ebc0dcbc4f7143"
metafile = true

[[files]]
file = "mods/corpse.pw.toml"
hash = "cf0ff107d6ea5200e6d09342501d1bce247dc9a3dd67729b8765d5a276686026"
metafile = true

[[files]]
file = "mods/create-central-kitchen.pw.toml"
hash = "dbdb686363922b46666480726b8470cbb8a6ed8386c5c3f20ff6ac06b0654e67"
metafile = true

[[files]]
file = "mods/create-connected.pw.toml"
hash = "aea6d37ae312cafb92d9456c9b16e7e8406ba03c5dab5c4ade19a204c509ec85"
metafile = true

[[files]]
file = "mods/create-dragons-plus.pw.toml"
hash = "082a37f089430e72bb56ec9ab1e6577796684727d706630118508e15b0c29c77"
metafile = true

[[files]]
file = "mods/create-jetpack.pw.toml"
hash = "1d8fce350ce2671f24579691c47bc178ee7b644751ecec5f068427058de0cd2b"
metafile = true

[[files]]
file = "mods/create-mobile-packages.pw.toml"
hash = "7cbcc68274747ac4ffb9f4a88f87c2fbcda7a2c267098173a279781ced0e25b6"
metafile = true

[[files]]
file = "mods/create-power-loader.pw.toml"
hash = "ee76dbe108ebf5cf68047f60ecabee5aeb029015253dc82c007b941a6d6cfcdf"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "d6043c928c34ce1f4ada544a49193f95c281665cf88d4931e73370ea02870bed"
metafile = true

[[files]]
file = "mods/diagonal-fences.pw.toml"
hash = "632743d54d410c8b78fb92c94d8f3bb6a7a3faed45171f91e554877f94f82163"
metafile = true

[[files]]
file = "mods/diagonal-walls.pw.toml"
hash = "bbc15c019fd260bbb9058b14a8e03232a55df77608d9aca466d051007d62abd2"
metafile = true

[[files]]
file = "mods/distraction-free-recipes.pw.toml"
hash = "f875588dab7596284ac4a4af91b7d2c650100111c6dfb51c7159ef523536ca65"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "990440461d18696ec496072dd118bf1ffbbe089080c47dcc7d17bf7ee245b018"
metafile = true

[[files]]
file = "mods/ender-potions.pw.toml"
hash = "cb2f885c7e5e5f7c65e37eb491478fff8f8017a6a01ebe610114a4d61fc1bce3"
metafile = true

[[files]]
file = "mods/enderscape.pw.toml"
hash = "dee101b4695257c023df362ae0e99f9ed7ca0f43bf943016f398e301b1678be4"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "af402152ceed21b9467f2a95a02a32b5c02af3b734a5b0a37e96dd34c694ec33"
metafile = true

[[files]]
file = "mods/etched.pw.toml"
hash = "3e11ffcdd1d2c77ac05bf2fbeb52f746491efbc8b2664e80aed8670856c0f686"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "44abae510395f12f9ea97b8296b2f72e25f18b9f3f2cc0ee42c0d9afd73fe0b3"
metafile = true

[[files]]
file = "mods/fast-ip-ping.pw.toml"
hash = "b9341d6f19a21f977f3d3b614b626ab182b4c48b0ad4583f8e33a18ffdd72840"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "018c7f1828e1d350684036c87f9c8b88041eb38fa5f89753296aedcb3f93ac9c"
metafile = true

[[files]]
file = "mods/figura.pw.toml"
hash = "8149cdb52f8798891b5287923f3235258703f72019a1c8f5419e764bbbbfd002"
metafile = true

[[files]]
file = "mods/forgified-fabric-api.pw.toml"
hash = "7d65677a7217902438defbdb64c924e91f5a119b06ad2a4bcb7e7d1d6dcd42d3"
metafile = true

[[files]]
file = "mods/framework.pw.toml"
hash = "11bc4d2951f2bbb0dd17c77534f05c909987e19203398558713bc515f441d5a2"
metafile = true

[[files]]
file = "mods/ftb-library-forge.pw.toml"
hash = "2c50b8333ac6557bf65aef87110d8ab234bc9143e5d3065af913dc3dd7b1092e"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "79dcaca4bfb4b7aedcb2c5fc5266d81b07d38acefdbf8ae0d7f8c142b69373c2"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "0eab211c9370a122e7471006e1ff3716e97b7b7a067804e0acecd0c97ffc3b6c"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "81a33f52a83db85c1df018106efe65a259482dcc2e65e725b721aac063e74401"
metafile = true

[[files]]
file = "mods/joy-of-painting.pw.toml"
hash = "250a60ad345454a739a4ed90779501c31c90f5be387c3e52816ced6713012e98"
metafile = true

[[files]]
file = "mods/just-enough-resources-jer.pw.toml"
hash = "8303ca85e25bde4ecb3d3f74de573d97e7f41d7502a3ae455454bdb32f2746b8"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "c8c9fccd7d99b0af6158d22670c8ace3e9abd747608c5e29e1637f70178864af"
metafile = true

[[files]]
file = "mods/lcbackport.pw.toml"
hash = "d0aa2439ec7df6ccf2fd8353bde30d0f045509d87b6a5bdad1490b92a6ff1eb6"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "57100c4b98ff0604b374e3e97480b7a1533e2b107a2246cbca9e13be5bd5cfce"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "484cf49e7852908261459bd2e094e0aa58f4550755d9d884606ebe838ab382ba"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
hash = "b7d6d4ba658eb8f73508a79b0cff9bd45f265239153a8793c73761024b707030"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "974bcb6109d987bb2fbc0bd344dddc6b5e3df2b0d523ed2e773fc7759fa58926"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "691a44fc96225647d9a258a40931434f0aba20c1fb81e0cb4590e82aaaf47ec7"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
hash = "05122fca54725773ed202a5d527a1b57f2a8eb8a57ef32b05a90759fda9ec829"
metafile = true

[[files]]
file = "mods/particle-rain.pw.toml"
hash = "86c688ed4fbeb2ea114cf51c09e476d0f9c4bc4cf63d5b5b927dfc0f4f486718"
metafile = true

[[files]]
file = "mods/perfect-parity-1-21-5.pw.toml"
hash = "49e0811fe174046317cba4a2f574938c6e09ce948903eb642339426f27340012"
metafile = true

[[files]]
file = "mods/perfect-parity-the-garden-awakens-edition.pw.toml"
hash = "e54d5ba962c244265678a3d13877d008b2d95e69c41e6135e5424e48e3997cc2"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "989b2aeb18f4004fb9b7932951de4b38ffa0fc6bf5360ac32ffe9af08391d04d"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "9b55dd1af2ee7a78fb4363b3111bbc2237572699c0e5a97d00381dcabdc7251a"
metafile = true

[[files]]
file = "mods/refurbished-furniture.pw.toml"
hash = "35eb897c9736c48125a8f86253bc5c0f6f1b3891127d7c300d00b0339167cd36"
metafile = true

[[files]]
file = "mods/rustic-delight.pw.toml"
hash = "5c40b97cbeb3afcb2d0e9831f0e5d6e8503fd92f05193f25d84718f3b06f0f57"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "90e005daa3742e4a0be52b7912de8e79ea1da752ee20d89511205fb9e238b4f1"
metafile = true

[[files]]
file = "mods/sinytra1343.pw.toml"
hash = "f9ce2a505c7eb22a4923d57076d6f942b96b26251b070fbca07672333e0f44fd"
metafile = true

[[files]]
file = "mods/slice-and-dice.pw.toml"
hash = "6b100c6847b82f48ac150816c2e9ce8fd590a4dc92a49e38634b7f6c6b5a2e71"
metafile = true

[[files]]
file = "mods/sodium-dynamic-lights.pw.toml"
hash = "4bde9ea7fd1867a1e1452c500676dd4c691514c24da64fae1905b1a12e185232"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "c5a18fb9305573838b957b3ea468bda48ac2adbc149333a6b7912eba81ccd0cf"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks-create-integration.pw.toml"
hash = "60eafc15811c83422b8e864732fc526fec0d35e190d857520125d77fd92cf2bd"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks.pw.toml"
hash = "d3ef4867e3ab6a7719cc63fac97a3bbf6bf09065387ee87f87544d40bae84c3b"
metafile = true

[[files]]
file = "mods/sophisticated-core.pw.toml"
hash = "4d089d75de8c9cde2d7bf931a0f8dd7a6590ff98cc7713f8f4b9be5a87310260"
metafile = true

[[files]]
file = "mods/sophisticated-storage-create-integration.pw.toml"
hash = "b2dd82a068e3fe45fe8c7b22efd599047fac853ca00fa497b04941650be3cab9"
metafile = true

[[files]]
file = "mods/sophisticated-storage.pw.toml"
hash = "2e2fe2506ff9e1ebade5ad6009b0a8e75be18a790a9703d3f83371c032daae46"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "2e4c8891ec22ca246b414728493ff52fe177bc9c4369ed23a5a80e8332e79c67"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "3773134fe0c46662174263269b77361287ba40bd90348a30f908b89df98e8e63"
metafile = true

[[files]]
file = "mods/tmrv.pw.toml"
hash = "ea1670317ee477db86bba796dcb249ba1873627be02b15730f948aff95431dd2"
metafile = true

[[files]]
file = "mods/trade-cycling.pw.toml"
hash = "acca3f6ac6b9a2b12076c0539d19962b45d41da7f53fa8d2ee3feb33a990554a"
metafile = true

[[files]]
file = "mods/trimmed.pw.toml"
hash = "48a3d2303e013e2c5ce4cbfec4d797a0066719434f795f564b7489b63c7b817e"
metafile = true

[[files]]
file = "mods/txnilib.pw.toml"
hash = "bf62fc87ede6198cc3ff0fc53ef0417d788e76f3f63e8ddc7a80da9872295eb5"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "a89d730673f93d3e592a089ec884110e70b95aee95dd01f0657eb16207e33b55"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "910a50b303528b05546d6e1b5f11c160b4d7810180f93d7542a2153d7c561466"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "02b910fbb42088a77284549274a3b28d0f80f5544778450a26c65bd23b6d0fb2"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "aa9070a0e763f00f0d0b325e9bb980e53faabe9854bae25f2e542a7b81b7492e"
metafile = true

[[files]]
file = "mods/youkaishomecoming.pw.toml"
hash = "a7a526b9362db210f20bdc5f64b400827c09a8f626cf0e35fe66b15d49c8f236"
metafile = true

[[files]]
file = "servers.dat"
hash = "c9821016c873fca9a3f7534de3a84d06fbb3ef162c1c245844aeb70f46d77a37"

[[files]]
file = "shaders/ComplementaryReimagined_r5.5.1.zip"
hash = "20897248a5fe91b33bf7fd4b75959c30aa2003df195297979a410ee37d3bb62f"

[[files]]
file = "shaders/ComplementaryUnbound_r5.5.1.zip"
hash = "61d133b24b6a92e46a3d7df791bb2ff163bbba10eed59df979b9bd727c24fbaf"
