name = "Niggacraft"
author = "oiipo"
version = "2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd72993b0221dfdd909a19c79a687bb542aee488be601180310a12b89f55a358"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.205"
