name = "Niggacraft"
author = "oiipo"
version = "2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa7b6a0bb12078e3fe8a1e63ba9280080f7287e1ae56f966e2e735c075a379ad"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
