name = "Niggacraft"
author = "oiipo"
version = "2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "88ba186419722ab9685438cebadd75fa70f65ab9e48c134c61b1d53210f5ea96"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
